import {mkenum, mknametable} from './util.js';

export const ComponentType = mkenum(
    'Position',
    'Tile',
    'Actor',
    'Solid',
    'Collider',
    'PlayerCharacter',
    'Memory',
    'Vision',
    'Opacity',
    'Door',
    'DownStairs',
    'UpStairs',
    'Combatant',
    'Health',
    'Defence',
    'Dodge',
    'Accuracy',
    'Attack',
    'Name',
    'Inventory',
    'Getable',
    'Ability',
    'Pushable',
    'CanPush',
    'Cooldown',
    'EquipmentSlot',
    'Timeout',
    'WalkTime',
    'CombatNeutral',
    'Noteworthy',
    'CombatEvent',
    'CombatEquipmentEvent',
    'Dead',
    'Poisoned',
    'Web',
    'WebProof'
);

export const ComponentNames = mknametable(ComponentType);
